### PR TITLE
Client and server

### PR DESCRIPTION
**Pull request by NinjaMeTimbers**
...es.

### CODE REVIEW

**Comment by unlair** [comment]
Looks good except World.cpp and Racer.cpp probably shouldn't be in this commit. Also I just pushed some new changes. Do you think you can pull from the current repository into your fork, then open a new pull request that only includes your changes, and no modifications to World.cpp or Racer.cpp??

**Comment by unlair** [comment]
Oh and the files you actually modified haven't been touched by me in my most recent push, so the above mentioned stuff shouldn't cause any problems for you

**Comment by unlair** [comment]
ONE more thing: Maybe the cpsc559 directory should be in the home directory instead of inside the cpsc585 directory. it's kind of weird having one visual studio project inside another project's directory instead of side-by-side

**Comment by NinjaMeTimbers** [comment]
Sorry, I thought I excluded the cpsc559 stuff from the commit. I still don't completely know what I'm doing with github... Also, I don't remember modifying world or racer at all... so I don't know what's up with that

**Comment by NinjaMeTimbers** [comment]
Actually now that I think about it, VS2010 complained about something to do with the formatting when I opened the file and I pressed ok it could fix it.

**Pull request closed without merging**
